/* 
 * Please note that this is an auto-generated file which is automatically generated whenever a target is built.
 */

#include <data.h>
#include <fcntl.h>
#include <i2c.h>
#include <proc_iox.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>

data_t* data;


/* Autogenerated Code Begins */
int initMetaData() {
	if((data = (data_t*) malloc(sizeof(data_t))) == NULL) { return 1; }
	if((data->pressure = (pressure_t*) malloc(sizeof(pressure_t))) == NULL) { return 1; }
	if((data->motion = (motion_t*) malloc(sizeof(motion_t))) == NULL) { return 1; }
	if((data->bms = (bms_t*) malloc(sizeof(bms_t))) == NULL) { return 1; }
	if((data->rms = (rms_t*) malloc(sizeof(rms_t))) == NULL) { return 1; }
	if((data->flags = (flags_t*) malloc(sizeof(flags_t))) == NULL) { return 1; }
	if((data->timers = (timers_t*) malloc(sizeof(timers_t))) == NULL) { return 1; }

	return 0;
}

int initData() { 
	// Initializes all data points
	if (initMetaData() != 0) {
		fprintf(stderr, "Failed to init meta data\n");
		return -1;
	}
	if (initPressureData() != 0) {
		fprintf(stderr, "Failed to init pressure data\n");
		return -1;
	}
	if (initMotionData() != 0) {
		fprintf(stderr, "Failed to init motion data\n");
		return -1;
	}
	if (initBmsData() != 0) {
		fprintf(stderr, "Failed to init bms data\n");
		return -1;
	}
	if (initRmsData() != 0) {
		fprintf(stderr, "Failed to init rms data\n");
		return -1;
	}
	if (initFlagData() != 0) {
		fprintf(stderr, "Failed to init flags data\n");
		return -1;
	}
	if (initTimerData() != 0) {
		fprintf(stderr, "Failed to init timers data\n");
		return -1;
	}

	// Initialize mutex
	if(pthread_mutex_init(&data->dataMutex, NULL) != 0) {
		return 1;
	}

	setDataState(0);
	return 0;
}

int initPressureData() { 
	// Initialize mutex
	if(pthread_mutex_init(&data->pressure->pressureMutex, NULL) != 0) {
		return 1;
	}

	setPressurePrimTank(0.0);
	setPressurePrimLine(0.0);
	setPressurePrimAct(0.0);
	setPressureSecTank(0.0);
	setPressureSecLine(0.0);
	setPressureSecAct(0.0);
	setPressureAmb(0.0);
	setPressurePv(0.0);
	return 0;
}

int initMotionData() { 
	// Initialize mutex
	if(pthread_mutex_init(&data->motion->motionMutex, NULL) != 0) {
		return 1;
	}

	setMotionPos(0.0f);
	setMotionVel(0.0f);
	setMotionAccel(0.0f);
	setMotionRetroCount(0);
	setMotionMissedRetro(0);
	return 0;
}

int initBmsData() { 
	// Initialize mutex
	if(pthread_mutex_init(&data->bms->bmsMutex, NULL) != 0) {
		return 1;
	}

	setBmsPackCurrent(0.0f);
	setBmsPackVoltage(0.0f);
	setBmsImdStatus(0);
	setBmsPackDCL(0);
	setBmsPackCCL(0);
	setBmsPackResistance(0);
	setBmsPackHealth(0);
	setBmsPackOpenVoltage(0.0f);
	setBmsPackCycles(0);
	setBmsPackAh(0);
	setBmsInputVoltage(0.0f);
	setBmsSoc(0);
	setBmsRelayStatus(0);
	setBmsHighTemp(0);
	setBmsLowTemp(0);
	setBmsAvgTemp(0);
	setBmsCellMaxVoltage(0.0f);
	setBmsCellMinVoltage(0.0f);
	setBmsCellAvgVoltage(0);
	setBmsMaxCells(0);
	setBmsNumCells(0);
	return 0;
}

int initRmsData() { 
	// Initialize mutex
	if(pthread_mutex_init(&data->rms->rmsMutex, NULL) != 0) {
		return 1;
	}

	setRmsIgbtTemp(0);
	setRmsGateDriverBoardTemp(0);
	setRmsControlBoardTemp(0);
	setRmsMotorTemp(0);
	setRmsMotorSpeed(0);
	setRmsPhaseACurrent(0);
	setRmsPhaseBCurrent(0);
	setRmsPhaseCCurrent(0);
	setRmsDcBusVoltage(0);
	setRmsLvVoltage(0);
	setRmsCanCode1(0);
	setRmsCanCode2(0);
	setRmsFaultCode1(0);
	setRmsFaultCode2(0);
	setRmsCommandedTorque(0);
	setRmsActualTorque(0);
	setRmsRelayState(0);
	setRmsElectricalFreq(0);
	setRmsDcBusCurrent(0);
	setRmsOutputVoltageLn(0);
	setRmsVSMCode(0);
	setRmsKeyMode(0);
	return 0;
}

int initFlagData() { 
	// Initialize mutex
	if(pthread_mutex_init(&data->flags->flagsMutex, NULL) != 0) {
		return 1;
	}

	setFlagsReadyPump(0);
	setFlagsPumpDown(0);
	setFlagsReadyCommand(0);
	setFlagsReadyToBrake(false);
	setFlagsPropulse(0);
	setFlagsEmergencyBrake(0);
	setFlagsShouldStop(0);
	setFlagsShutdown(0);
	setFlagsShouldBrake(false);
	setFlagsIsConnected(false);
	setFlagsBrakeInit(false);
	setFlagsBrakePrimAct(false);
	setFlagsBrakeSecAct(false);
	setFlagsBrakePrimRetr(false);
	setFlagsBrakeSecRetr(false);
	setFlagsClrMotionData(false);
	return 0;
}

int initTimerData() { 
	// Initialize mutex
	if(pthread_mutex_init(&data->timers->timersMutex, NULL) != 0) {
		return 1;
	}

	setTimersStartTime(0);
	setTimersOldRetro(0);
	setTimersLastRetro(0);
	for(int i = 0; i < 3; i++)
		setTimersLastRetros(0, i);
	setTimersCrawlTimer(0);
	return 0;
}
/* Autogenerated Code Ends */

